import { useEffect, useState } from "react";
import { PageHeader, Panel, Spinner, EmptyState } from "../components/PageHeader";
import api from "../api/client";

export default function Figures({ runId }) {
  const [figures, setFigures] = useState([]);
  const [loading, setLoading] = useState(true);
  const [lightbox, setLightbox] = useState(null);

  useEffect(() => {
    setLoading(true);
    api
      .listFigures(runId || "")
      .then((r) => setFigures(r.figures))
      .finally(() => setLoading(false));
  }, [runId]);

  const grouped = figures.reduce((acc, f) => {
    (acc[f.figure_type] ||= []).push(f);
    return acc;
  }, {});

  return (
    <>
      <PageHeader
        eyebrow="Publication-quality exports"
        title="Figures"
        description="SVG and PNG figures generated by the visualization engine. Click to enlarge; download the SVG for LaTeX inclusion."
      />

      {loading ? (
        <Panel>
          <Spinner />
        </Panel>
      ) : figures.length === 0 ? (
        <Panel>
          <EmptyState
            title="No figures generated yet"
            description="Figures are produced during the post-processing stage of an experiment run."
          />
        </Panel>
      ) : (
        Object.entries(grouped).map(([type, figs]) => (
          <Panel key={type} title={type.replace(/_/g, " ")} subtitle={`${figs.length} figure(s)`}>
            <div className="figure-grid">
              {figs.map((f) => (
                <button
                  key={f.figure_id}
                  className="figure-card"
                  onClick={() => setLightbox(f)}
                >
                  <img src={f.png_url} alt={f.title} loading="lazy" />
                  <span className="figure-card-title">{f.title}</span>
                </button>
              ))}
            </div>
          </Panel>
        ))
      )}

      {lightbox && (
        <div className="lightbox" onClick={() => setLightbox(null)}>
          <div className="lightbox-inner" onClick={(e) => e.stopPropagation()}>
            <img src={lightbox.png_url} alt={lightbox.title} />
            <div className="lightbox-foot">
              <span>{lightbox.title}</span>
              <div className="lightbox-actions">
                {lightbox.svg_url && (
                  <a href={lightbox.svg_url} download className="lightbox-link">
                    Download SVG
                  </a>
                )}
                <a href={lightbox.png_url} download className="lightbox-link">
                  Download PNG
                </a>
                <button className="lightbox-close" onClick={() => setLightbox(null)}>
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
